### ISSUE TITLE
LibreCHovid tells me that my phon has Google 

### ISSUE THREAD

**Issue by Mannshoch** [c4dt/dp3t-app-android-ch#2]
I only installed lineage and microg but LibreCHovid tells me that I have Google on phone.

**Comment by cgrigis** [comment]
Thank you for your report!
To make sure I understand correctly, you have microG installed system-wide, right? I haven't tried that case (only plain LineageOS, or vendor OS with GMS), so I guess the GMS check gets confused by the system-wide microG. I will look into it.

**Comment by Mannshoch** [comment]
Yes that's correct.

- LineageOS 17.1 
- unifiednlp (https://blog.eowyn.net/unifiednlp/)
- magisk (because I use AFWall and AdAway )

**Comment by cgrigis** [comment]
After some investigation, this is actually not easy to solve, because by its very nature, microG is very good at pretending to be the real GMS (that's the whole point!). So the app saying you are running GMS shows it's been properly fooled. :)
For the moment, I would suggest to just ignore the message and proceed with the app (the message only comes up at the first run anyway).

**Comment by Mannshoch** [comment]
No Problem. But may you could enhance the Dialog with this additional information.
By the way. Does unifiednlp or any other microG help Librecovid in working? As far I know Google added the special code for covid traceing to the Google Play service.

**Comment by cgrigis** [comment]
> By the way. Does unifiednlp or any other microG help Librecovid in working? As far I know Google added the special code for covid traceing to the Google Play service.

Yes, microG is essential for LibreCHovid to work. The app actually comes bundled with the subset of microG libraries that reimplement the Exposure Notification functionality from Google. This way, it can run even on devices which do not already have microG installed.

**Comment by cgrigis** [comment]
The latest version has a slightly modified message, including a note that indicates the popup could be due to having microG installed system-wide.

**Comment by julianfairfax** [comment]
> > By the way. Does unifiednlp or any other microG help Librecovid in working? As far I know Google added the special code for covid traceing to the Google Play service.
> 
> Yes, microG is essential for LibreCHovid to work. The app actually comes bundled with the subset of microG libraries that reimplement the Exposure Notification functionality from Google. This way, it can run even on devices which do not already have microG installed.

Would it be possible to also add a view of the encounters? This can't be seen through the app and since I don't have microG installed system-wide, I'm not able to see it at all. Thanks for making this app!
