### ISSUE TITLE
Cannot grant bluetooth permission

### ISSUE THREAD

**Issue by sbor23** [c4dt/dp3t-app-android-ch#4]
First of all, thanks so much for your effort in providing this google- and microg-free solution! I've successfully used a build from github since february or so.
(I guess it was successful, I've never gotten a report so that's a success in itself.) ;)

However I just switched to the f-droid version and during onboarding I couldn't grant the necessary bluetooth permission!
The "grant" button exists but it has no effect.

Version: 1.5.0+nogaen-3 from F-Droid
Device: beryllium (Xiaomi Pocophone F1)
OS: LineageOS 18.1 (no GApps, no Microg, no other customizations...)

**Comment by cgrigis** [comment]
Hello, and thank you for your feedback! :-)

Could you give me more information regarding the OS and version you are using? That will help me to try and reproduce the issue here. Thanks!

**Comment by sbor23** [comment]
I updated the post with specs.

**Comment by cgrigis** [comment]
Apologies for the long delay.

Indeed, I was able to reproduce the problem on LineageOS 18.1 (17.1 does not exhibit this issue).

Not yet sure what is causing it.

My current workaround is to manually grant the permission: long-click on the app icon, "App Info", "Permissions", and grant the "Location" permission "all the time". Going back to the application, it should allow you to proceed.

**Comment by cgrigis** [comment]
Opened an issue with microG: microg/GmsCore#1519

**Comment by sbor23** [comment]
Thanks for going lengths to confirm this. I tried the workaround too but was missing the "bluetooth" permission, didn't anticipate I have to check the "Location" for this. Oh well...
But it works this way, thanks!

(Feel free to close if you don't want to keep it as a reminder about the upstream issue.)

**Comment by ale5000-git** [comment]
The permission granting is fixed inside microG.

**Comment by ale5000-git** [comment]
@cgrigis: Any plan to release the update with the fix soon?
