### ISSUE TITLE
Update to 2.0

### ISSUE THREAD

**Issue by oscaropenness** [c4dt/dp3t-app-android-ch#5]
The official Swisscovid-App has received a major update to 2.0 with new features like the checkin function.
Will the LibreCHovid app also be updated to this version?

**Comment by cgrigis** [comment]
Thank you for your message!

Yes, I am working on it. :)  There is a first release on here, and I will work on submitting to F-Droid hopefully tomorrow. It will actually be based on 2.0.1.

**Comment by cgrigis** [comment]
The update was merged into F-Droid, it should hopefully appear on the store within a few days.

**Comment by cgrigis** [comment]
@oscaropenness 2.0.1 is available on F-Droid :)
